### ISSUE TITLE
Make the function/event/variable tag a footer

### ISSUE THREAD

**Issue by albertocuestacanada** [soldocjs/soldoc#10]
The same that there is a coloured line at the top of each method/event/variable, there should be a ~10px footer in the same colour with the method/event/variable/constructor word within.

**Comment by obernardovieira** [comment]
I think it's going to be like a bit overwhelming.
But I want to move to Bulma #11 so, I think it will change a bit the page styling, and may not worth to have those colors. Let's see.

**Comment by obernardovieira** [comment]
This is now deprecated as the template was changed, and the support for external templates, gitbook and docsify is supported for the 0.1.1 release.
